### ISSUE TITLE
Plugin completely broken - easing not a function

### ISSUE THREAD

**Issue by neonoxGER** [ehynds/jquery-ui-multiselect-widget#649]
The plugin is completely broken, even the demo files don't work with jQuery 1.12.

After clicking on the menu and hover over an item, the message **n.easing[this.easing] is not a function** appears.

Any ideas for a fix?

**Comment by neonoxGER** [comment]
Bower failed to load the current version.

**Comment by mlh758** [comment]
@neonoxGER I'll look into getting that fixed. I haven't worked with Bower before.

**Comment by mlh758** [comment]
@neonoxGER Is a specific version set in your bower.json, and does a bower update help?

**Comment by neonoxGER** [comment]
```
{
  "name": "jquery-ui-multiselect-widget",
  "homepage": "https://github.com/ehynds/jquery-ui-multiselect-widget",
  "version": "1.4.1",
  "_release": "1.4.1",
  "_resolution": {
    "type": "version",
    "tag": "1.4.1",
    "commit": "a742676f95af9ab6f5023fc5de193454f08b7fe6"
  },
  "_source": "https://github.com/ehynds/jquery-ui-multiselect-widget.git",
  "_target": "^1.4.1",
  "_originalSource": "jquery-ui-multiselect-widget",
  "_direct": true
}
```

**Comment by mlh758** [comment]
@neonoxGER I might be wrong but that appears to be looking for version 1.4.1 which was released in 2010. 1.14 is the current latest.

**Comment by neonoxGER** [comment]
I know, but I have no idea, why bower gets this version info.
I guess you have to put a .bower.json file into your repository.
